const words = [
    "house",
    "dog",
    "cat",
    "food",
    "water",
    "drink",
    "eat",
    "sleep",
    "work",
    "play",
    "love",
    "friend",
    "family",
    "home",
    "car",
    "bike",
    "walk",
    "run",
    "jump",
    "sit",
    "stand",
    "talk",
    "listen",
    "read",
    "write",
    "learn",
    "study",
    "watch",
    "see",
    "hear",
    "feel",
    "touch",
    "smell",
    "taste",
    "happy",
    "sad",
    "angry",
    "excited",
    "bored",
    "tired",
    "hungry",
    "thirsty",
    "hot",
    "cold",
    "rain",
    "sun",
    "wind",
    "snow",
    "cloud",
    "sky",
    "day",
    "night",
    "morning",
    "afternoon",
    "evening",
    "today",
    "yesterday",
    "tomorrow",
    "week",
    "month",
    "year",
    "sunrise",
    "sunset",
    "moon",
    "star",
    "earth",
    "nature",
    "tree",
    "flower",
    "grass",
    "river",
    "lake",
    "ocean",
    "mountain",
    "hill",
    "valley",
    "beach",
    "desert",
    "forest",
    "park",
    "garden",
    "street",
    "road",
    "bridge",
    "building",
    "city",
    "town",
    "village",
    "country",
    "world",
    "continent",
    "island",
    "oasis",
    "cave",
    "canyon",
    "waterfall",
    "rainbow",
    "cloudy",
    "sunny",
    "windy",
    "stormy",
    "foggy",
    "clear",
    "bright",
    "dark",
    "color",
    "red",
    "blue",
    "green",
    "yellow",
    "orange",
    "purple",
    "pink",
    "white",
    "black",
    "gray",
    "brown",
    "silver",
    "gold",
    "metal",
    "wood",
    "plastic",
    "glass",
    "paper",
    "cloth",
    "leather",
    "stone",
    "brick",
    "concrete",
    "sand",
    "dirt",
    "mud",
    "rock",
    "pebble",
    "sandwich",
    "breakfast",
    "lunch",
    "dinner",
    "snack",
    "fruit",
    "vegetable",
    "meat",
    "fish",
    "chicken",
    "beef",
    "pork",
    "milk",
    "egg",
    "bread",
    "butter",
    "cheese",
    "rice",
    "noodle",
    "pasta",
    "soup",
    "salad",
    "cake",
    "cookie",
    "candy",
    "chocolate",
    "ice cream",
    "tea",
    "coffee",
    "juice",
    "water",
    "soda",
    "wine",
    "beer",
    "whiskey",
    "vodka",
    "rum",
    "gin",
    "brandy",
    "cocktail",
    "mocktail",
    "glass",
    "cup",
    "plate",
    "bowl",
    "fork",
    "spoon",
    "knife",
    "napkin",
    "table",
    "chair",
    "sofa",
    "bed",
    "pillow",
    "blanket",
    "sheet",
    "towel",
    "mirror",
    "toothbrush",
    "toothpaste",
    "soap",
    "shampoo",
    "conditioner",
    "lotion",
    "perfume",
    "deodorant",
    "tissue",
    "bandaid",
    "medicine",
    "doctor",
    "hospital",
    "nurse",
    "patient",
    "sick",
    "healthy",
    "exercise",
    "sport",
    "game",
    "ball",
    "team",
    "player",
    "coach",
    "referee",
    "win",
    "lose",
    "tie",
    "score",
    "goal",
    "run",
    "jump",
    "swim",
    "bike",
    "hike",
    "dance",
    "sing",
    "music",
    "song",
    "guitar",
    "piano",
    "violin",
    "drum",
    "flute",
    "trumpet",
    "saxophone",
    "clarinet",
    "accordion",
    "banjo",
    "ukulele",
    "harp",
    "viola",
    "cello",
    "bass",
    "keyboard",
    "microphone",
    "speaker",
    "headphone",
    "earphone",
    "camera",
    "photo",
    "video",
    "film",
    "screen",
    "movie",
    "show",
    "watch",
    "listen",
    "play",
    "read",
    "write",
    "draw",
    "paint",
    "color",
    "sketch",
    "picture",
    "photo",
    "video",
    "movie",
    "book",
    "novel",
    "story",
    "poem",
    "essay",
    "article",
    "magazine",
    "newspaper",
    "blog",
    "website",
    "internet",
    "computer",
    "phone",
    "tablet",
    "device",
    "app",
    "software",
    "program",
    "game",
    "social",
    "media",
    "network",
    "facebook",
    "twitter",
    "instagram",
    "snapchat",
    "tiktok",
    "youtube",
    "linkedin",
    "pinterest",
    "reddit",
    "whatsapp",
    "messenger",
    "telegram",
    "wechat",
    "line",
    "zoom",
    "skype",
    "discord",
    "email",
    "message",
    "chat",
    "call",
    "video",
    "voice",
    "photo",
    "video",
    "audio",
    "text",
    "file",
    "document",
    "note",
    "letter",
    "email",
    "website",
    "page",
    "link",
    "search",
    "find",
    "browse",
    "surf",
    "download",
    "upload",
    "install",
    "uninstall",
    "update",
    "upgrade",
    "backup",
    "restore",
    "save",
    "delete",
    "copy",
    "paste",
    "cut",
    "undo"];
   
  
let chosenWord = '';
let guessedLetters = [];
let remainingGuesses = 6;

const wordContainer = document.getElementById('word-container');
const guessContainer = document.getElementById('guess-container');
const message = document.getElementById('message');
const resetButton = document.getElementById('reset-button');

function initializeGame() {
    chosenWord = words[Math.floor(Math.random() * words.length)];
    guessedLetters = [];
    remainingGuesses = 6;
    displayWord();
    displayGuesses();
    message.textContent = '';
}

function displayWord() {
    wordContainer.innerHTML = '';
    chosenWord.split('').forEach(letter => {
        const span = document.createElement('span');
        span.textContent = guessedLetters.includes(letter) ? letter : '_';
        wordContainer.appendChild(span);
    });
}

function displayGuesses() {
    guessContainer.textContent = `Guesses Left: ${remainingGuesses}`;
}

function checkGameStatus() {
    const displayedWord = wordContainer.textContent.replace(/ /g, '');
    if (displayedWord === chosenWord) {
        message.textContent = 'Congratulations! You won!';
    } else if (remainingGuesses === 0) {
        message.textContent = `Game over! The word was "${chosenWord}". Try again!`;
    }
}

function updateGuess(letter) {
    if (!guessedLetters.includes(letter)) {
        guessedLetters.push(letter);
        if (!chosenWord.includes(letter)) {
            remainingGuesses--;
        }
        displayWord();
        displayGuesses();
        checkGameStatus();
    }
}

document.addEventListener('DOMContentLoaded', initializeGame);

resetButton.addEventListener('click', initializeGame);

document.addEventListener('keypress', e => {
    const letter = e.key.toLowerCase();
    if (/[a-z]/.test(letter)) {
        updateGuess(letter);
    }
});
